### ISSUE TITLE
proxy_testscript.py is failing for NR mode. 

### ISSUE THREAD

**Issue by pragnyakiri** [EpiSci/oai-lte-5g-multi-ue-proxy#19]
proxy_testscript.py is failing for NR mode. 
I am following the instructions given in your README.md file. gNB conf file is updated with the AMF IP address and the NRUE information has been added in 5G CN database.  5G CN is already running in basic-nrf scenario.

$sudo ./proxy_testscript.py --num-ues 1 --mode=nr
>>> proxy_testscript.py: INFO: gNB node number 1
>>> proxy_testscript.py: INFO: nr-UE node number 2
>>> proxy_testscript.py: INFO: Core pattern was: '/tmp/coredump-%P\n'
>>> proxy_testscript.py: INFO: Launch gNB: ./gNB.log
>>> proxy_testscript.py: INFO: Launch Proxy: ./nfapi.log
>>> proxy_testscript.py: INFO: Launch nrUE1: ./NRUE1.log
>>> proxy_testscript.py: INFO: proxy process is still running, which is good
>>> proxy_testscript.py: INFO: gNB process is still running, which is good
>>> proxy_testscript.py: INFO: NRUE1 process is still running, which is good
>>> proxy_testscript.py: INFO: kill main simulation processes...
>>> proxy_testscript.py: INFO: kill main simulation processes...done
>>> proxy_testscript.py: INFO: Compress /home/dolcera/oai-lte-multi-ue-proxy/nfapi.log to ./nfapi-proxy.log.bz2
>>> proxy_testscript.py: INFO: Compress ./gNB.log to ./gNB.log.bz2
>>> proxy_testscript.py: INFO: Compress ./NRUE1.log to ./NRUE1.log.bz2
>>> proxy_testscript.py: INFO: No core files
>>> proxy_testscript.py: INFO: No eNB in this scenario
>>> proxy_testscript.py: INFO: No UEs in this scenario
>>> proxy_testscript.py: INFO: Scanning ./gNB.log.bz2
>>> proxy_testscript.py: ERROR: gNB failed -- found 1/6 {'config'}
>>> proxy_testscript.py: INFO: Scanning ./NRUE1.log.bz2
>>> proxy_testscript.py: ERROR: NRUE1 failed -- found 0/5 set()
>>> proxy_testscript.py: ERROR: NRUE1 failed -- missed 5 {'msg3-sent', 'msg4-rcvd', 'mib-rcvd', 'rar-rcvd', 'sib1-decoded'}
>>> proxy_testscript.py: CRITICAL: 1 of 1 NRUEs failed
>>> proxy_testscript.py: WARNING: 1566 errors, 0 warnings, 0 stack traces, 0 sanitizer issues in ./nfapi-proxy.log.bz2
>>> proxy_testscript.py: INFO: No file ./eNB.log.bz2
>>> proxy_testscript.py: WARNING: 6 errors, 0 warnings, 0 stack traces, 0 sanitizer issues in ./gNB.log.bz2
>>> proxy_testscript.py: WARNING: 726 errors, 0 warnings, 0 stack traces, 0 sanitizer issues in ./NRUE1.log.bz2
>>> proxy_testscript.py: CRITICAL: FAILED

Attaching gNB, NRUE and nfapi log files.
Any pointers regarding this will be helpful.
[nrue.log](https://github.com/EpiSci/oai-lte-5g-multi-ue-proxy/files/8444199/nrue.log)
[nfapi.log](https://github.com/EpiSci/oai-lte-5g-multi-ue-proxy/files/8444201/nfapi.log)
[gnb.log](https://github.com/EpiSci/oai-lte-5g-multi-ue-proxy/files/8444202/gnb.log)

**Comment by melissa-elkadi** [comment]
Hi there,

I apologize for getting back to you so late, I did not see this. Can you please indicate which OAI branch you are using? When I look at the logs I see the following error logs, which are pretty bad: `3005122142270 [E]  826099456: pullarray32: pullarray32 no space in buffer`

It seems like there is a mismatch in the OAI nFAPI code and the Proxy nFAPI code. We have seen this in the past when the versions of OAI and proxy are not matching. At this moment, May 16th 2022, you should be able to see passing tests with the OAI develop branch and the Proxy master branch. I apologize again for any inconvenience.

-Mel

**Comment by jordan-taylor7** [comment]
Hi, I'm having that exact same issue. OAI is up to date with the develop branch and the proxy is up to date with the master branch, and the proxytestscript is outputting the same error as above in NR mode. Any help you could provide would be greatly appreciated. Thanks!

**Comment by melissa-elkadi** [comment]
Hi there,

Are you able to add your logs here? I just pulled the lastest develop and ran with the proxy master branch and the NR UEs pass. The gNB also passes but unfortunately the OAI code recently removed several LOG_A logs (analysis logs used for test reporting) so the test report shows a fail, when it in fact passes. 

I am curious to see if your logs show the same `pullarray32: pullarray32 no space in buffer`, becasue I cannot produce that problem. The pullarray errors are almost always related to a mistmatch in the nFAPI code. 

For the LOG_A's in the OAI code, there is an approved MR that should add these back in within the next few days (see MR [1578](https://gitlab.eurecom.fr/oai/openairinterface5g/-/merge_requests/1578)). Furthremore, you can look in the gNB logs, you can look for `[NR_MAC] A (UE RNTI 0x6198) Received Ack of RA-Msg4. CBRA procedure succeeded!` and this indicates the RA procedure between the NR UE and the gNB is complete.

**Comment by melissa-elkadi** [comment]
Thank you for providing the logs. It looks like the NR UE and gNB are not properly getting connected via the proxy at all. I am not seeing any error indications, just simply no connection between the gNB/NRUE and the proxy

Can you tell me a little bit about the machine you are running on? The linux version, #CPUs, etc? Also, is checksctp returning the SCTP is supported on your machine? And the 127.0.0.2 interface is up?

Also, are you trying to run with the 5GCN? If so, your gNB launch should **not** include the --noS1 flag. To run with the 5GCN, you should run with the advanced options to properly select the correct flags (i.e., not having the --noS1 flag).

**Comment by jordan-taylor7** [comment]
I'm using an Intel NUC running Ubuntu 20.04 version 5.4.0-107-lowlatency and SCTP is supported. Currently, I am not trying to run with 5GCN. I ran the command for the 127.0.0.2 interface, here's the updated logs.
[gnb.log](https://github.com/EpiSci/oai-lte-5g-multi-ue-proxy/files/8881161/gnb.log)
[nfapi-proxy.log](https://github.com/EpiSci/oai-lte-5g-multi-ue-proxy/files/8881162/nfapi-proxy.log)
[NRUE1.log](https://github.com/EpiSci/oai-lte-5g-multi-ue-proxy/files/8881163/NRUE1.log)

**Comment by melissa-elkadi** [comment]
Awesome! Thanks! The gNB logs show that the CBRA procedure passed, which indicates a passing test. The CBRA procedure passing log is not found in the proxy_testscript because the log was mistakenly modified in the OAI code base. As mentioned previously, there is an approved MR to solve this, and then the test will indicate a pass. Looks like things are working well!

**Comment by jordan-taylor7** [comment]
Great! Thanks so much for your help :)

**Comment by melissa-elkadi** [comment]
Anytime!
